name: pediextest12
channels:
  - conda-forge
  - defaults
dependencies:
  # Python dependencies
  - python=3.9
  - pyyaml
  - networkx
  - matplotlib
  - graphviz
  - pandas

  # R dependencies
  - r-base
  - r-essentials  # Includes basic R tools like install.packages
  - r-devtools     # For GitHub installation if needed

  # Additional tools
  - pip

